'use client'

import { useState, useEffect } from 'react'
import Stepper from '@/components/Stepper'
import { loadReport, loadSession, markStepComplete } from '@/lib/session'
import { reportToJSON, type GovernanceReport, type EnrichedViolation } from '@/lib/governance'

// ─── Design Tokens ──────────────────────────────────────────
const T = {
  bg: '#08090d', surface: '#0c0e12', surface2: '#111318',
  border: '#1a1d24', border2: '#252830',
  green: '#00e087', greenDim: '#00e08718',
  red: '#ff4070', redDim: '#ff407018',
  amber: '#ffb830', amberDim: '#ffb83018',
  blue: '#4090ff', blueDim: '#4090ff18',
  purple: '#a855f7', purpleDim: '#a855f718',
  muted: '#6b7280', dim: '#3a3f4a',
  text: '#e8eaf0', textBright: '#f8f9fb',
}
const mono = "'JetBrains Mono', 'DM Mono', monospace"
const syne = "'Syne', sans-serif"
const sans = "'DM Sans', system-ui, sans-serif"

// ─── Helpers ────────────────────────────────────────────────

function scoreColor(score: number): string {
  if (score >= 90) return T.green
  if (score >= 60) return T.amber
  return T.red
}

function severityMeta(sev: string): { color: string; dim: string; label: string } {
  if (sev === 'auto-fix') return { color: T.green, dim: T.greenDim, label: 'AUTO-FIXED' }
  if (sev === 'warn') return { color: T.amber, dim: T.amberDim, label: 'WARNING' }
  return { color: T.red, dim: T.redDim, label: 'BLOCKED' }
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })
  } catch { return iso }
}

function reportToMarkdown(report: GovernanceReport, company: string): string {
  const lines: string[] = []
  lines.push(`# Governance Report`)
  lines.push('')
  lines.push(`**Company:** ${company}`)
  lines.push(`**Scanned:** ${report.fixtureName} (${report.fixtureSource})`)
  lines.push(`**Date:** ${formatDate(report.timestamp)}`)
  lines.push(`**Score:** ${report.overallScore} -> ${report.afterScore}`)
  lines.push('')
  lines.push(`## Category Scores`)
  lines.push('')
  for (const c of report.categories) {
    const bar = '\u2588'.repeat(Math.round(c.score / 5)) + '\u2591'.repeat(20 - Math.round(c.score / 5))
    lines.push(`- **${c.name}**: ${c.score}/100  ${bar}`)
  }
  lines.push('')

  const autoFixed = report.violations.filter(v => v.fixApplied)
  const warnings = report.violations.filter(v => !v.fixApplied && v.severity === 'warn')
  const blocked = report.violations.filter(v => !v.fixApplied && v.severity === 'block')

  if (autoFixed.length > 0) {
    lines.push(`## Auto-Fixed (${autoFixed.length})`)
    lines.push('')
    for (const v of autoFixed) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.fixDescription}`)
    }
    lines.push('')
  }

  if (warnings.length > 0) {
    lines.push(`## Warnings (${warnings.length})`)
    lines.push('')
    for (const v of warnings) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.evidence}`)
      lines.push(`  _Recommended:_ ${v.fixDescription}`)
    }
    lines.push('')
  }

  if (blocked.length > 0) {
    lines.push(`## Blocked (${blocked.length})`)
    lines.push('')
    for (const v of blocked) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.evidence}`)
      lines.push(`  _Action required:_ ${v.fixDescription}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('Generated by [muteform](https://muteform.com)')
  return lines.join('\n')
}

// ─── Visual Preview for Violations ──────────────────────────

function ViolationPreview({ v }: { v: EnrichedViolation }) {
  if (v.type === 'color_token') {
    const hex = v.evidence.match(/#[0-9a-fA-F]{6}/)?.[0] || '#ff0000'
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}>
        <div style={{ width: 18, height: 18, borderRadius: 4, background: hex, border: `1px solid ${T.border2}`, flexShrink: 0 }} />
        <span style={{ fontFamily: mono, fontSize: 10, color: T.muted }}>{hex}</span>
        {v.suggestedFix && v.suggestedFix.startsWith('#') && (
          <>
            <span style={{ fontFamily: mono, fontSize: 10, color: T.dim }}>{'\u2192'}</span>
            <div style={{ width: 18, height: 18, borderRadius: 4, background: v.suggestedFix, border: `1px solid ${T.border2}`, flexShrink: 0 }} />
            <span style={{ fontFamily: mono, fontSize: 10, color: T.green }}>{v.suggestedFix}</span>
          </>
        )}
      </div>
    )
  }

  if (v.type === 'spacing') {
    const cur = parseInt(v.evidence.match(/(\d+)/)?.[1] || '10')
    const sug = parseInt(v.suggestedFix.match(/(\d+)/)?.[1] || String(cur))
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}>
        <div style={{ width: Math.min(cur * 1.5, 48), height: 8, borderRadius: 3, background: `${T.red}80` }} />
        <span style={{ fontFamily: mono, fontSize: 10, color: T.muted }}>{cur}px</span>
        <span style={{ fontFamily: mono, fontSize: 10, color: T.dim }}>{'\u2192'}</span>
        <div style={{ width: Math.min(sug * 1.5, 48), height: 8, borderRadius: 3, background: `${T.green}80` }} />
        <span style={{ fontFamily: mono, fontSize: 10, color: T.green }}>{sug}px</span>
      </div>
    )
  }

  return (
    <div style={{ fontFamily: sans, fontSize: 11, color: T.muted, marginTop: 4 }}>
      {v.fixDescription}
    </div>
  )
}

// ─── Section Header ─────────────────────────────────────────

function SectionHeader({ label, count, color, dimColor }: {
  label: string; count: number; color: string; dimColor: string
}) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 10,
      padding: '14px 0', marginTop: 28,
      borderBottom: `1px solid ${T.border}`,
    }}>
      <span style={{
        fontFamily: mono, fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
        color, background: dimColor,
        padding: '3px 10px', borderRadius: 4,
        border: `1px solid ${color}33`,
      }}>
        {label}
      </span>
      <span style={{ fontFamily: mono, fontSize: 12, fontWeight: 600, color }}>{count}</span>
      <div style={{ flex: 1, height: 1, background: T.border }} />
    </div>
  )
}

// ─── Violation Card ─────────────────────────────────────────

function ViolationCard({ v, index }: { v: EnrichedViolation; index: number }) {
  const sev = severityMeta(v.severity)
  return (
    <div style={{
      padding: '14px 18px', background: T.surface,
      border: `1px solid ${v.fixApplied ? T.green + '22' : T.border}`,
      borderRadius: 10, marginTop: 8,
      borderLeft: `3px solid ${sev.color}22`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: sans, fontSize: 13, fontWeight: 600,
            color: T.textBright, lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: mono, fontSize: 10, color: T.dim,
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: mono, fontSize: 8, fontWeight: 600, letterSpacing: '0.06em',
          color: T.muted, background: T.surface2,
          padding: '3px 8px', borderRadius: 4,
          border: `1px solid ${T.border}`, whiteSpace: 'nowrap', flexShrink: 0,
        }}>
          {v.ruleSource}
        </span>
      </div>

      <div style={{
        fontFamily: sans, fontSize: 12, color: T.muted,
        marginTop: 8, lineHeight: 1.5,
      }}>
        {v.evidence}
      </div>

      <ViolationPreview v={v} />
    </div>
  )
}

// ─── Copy Button ────────────────────────────────────────────

function CopyButton({ label, onCopy }: { label: string; onCopy: () => void }) {
  const [copied, setCopied] = useState(false)

  const handleClick = () => {
    onCopy()
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button onClick={handleClick} style={{
      fontFamily: mono, fontSize: 11, fontWeight: 600,
      padding: '10px 20px', borderRadius: 8, cursor: 'pointer',
      background: copied ? T.greenDim : T.surface,
      color: copied ? T.green : T.textBright,
      border: `1px solid ${copied ? T.green + '44' : T.border}`,
      letterSpacing: '0.04em',
      transition: 'all 0.2s',
    }}>
      {copied ? 'Copied!' : label}
    </button>
  )
}

// ─── Main Page ──────────────────────────────────────────────

export default function ReportPage() {
  const [report, setReport] = useState<GovernanceReport | null>(null)
  const [company, setCompany] = useState('')
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    const r = loadReport() as GovernanceReport | null
    const session = loadSession()
    setReport(r)
    setCompany(session.user?.company || 'Your Company')
    setLoaded(true)
    markStepComplete(3)
  }, [])

  if (!loaded) return null

  if (!report) {
    return (
      <div style={{ minHeight: '100vh', background: T.bg, color: T.text }}>
        <Stepper />
        <div style={{
          maxWidth: 900, margin: '0 auto', padding: '80px 20px',
          textAlign: 'center',
        }}>
          <div style={{
            fontFamily: sans, fontSize: 18, fontWeight: 600,
            color: T.textBright, marginBottom: 12,
          }}>
            No report available. Run a scan first.
          </div>
          <a href="/scan" style={{
            fontFamily: mono, fontSize: 12, color: T.green,
            textDecoration: 'none',
            padding: '10px 24px', borderRadius: 8,
            background: T.greenDim,
            border: `1px solid ${T.green}33`,
            display: 'inline-block', marginTop: 8,
          }}>
            Go to Scan
          </a>
        </div>
      </div>
    )
  }

  const autoFixed = report.violations.filter(v => v.fixApplied)
  const warnings = report.violations.filter(v => !v.fixApplied && v.severity === 'warn')
  const blocked = report.violations.filter(v => !v.fixApplied && v.severity === 'block')

  const beforeColor = scoreColor(report.overallScore)
  const afterColor = scoreColor(report.afterScore)
  const delta = report.afterScore - report.overallScore

  return (
    <div style={{ minHeight: '100vh', background: T.bg, color: T.text }}>
      <Stepper />

      <div style={{ maxWidth: 900, margin: '0 auto', padding: '32px 20px 100px' }}>

        {/* ─── Report Header ──────────────────────────────── */}
        <div style={{
          background: T.surface, border: `1px solid ${T.border}`,
          borderRadius: 14, padding: '28px 32px', marginBottom: 24,
        }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 24 }}>
            {/* Left: metadata */}
            <div style={{ flex: 1, minWidth: 280 }}>
              <div style={{
                fontFamily: syne, fontSize: 22, fontWeight: 700,
                color: T.textBright, marginBottom: 16,
              }}>
                Governance Report
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '6px 16px' }}>
                <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.04em' }}>Company</span>
                <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>{company}</span>

                <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.04em' }}>Design System</span>
                <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>Acme Design System</span>

                <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.04em' }}>Scanned</span>
                <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>
                  {report.fixtureName} <span style={{ color: T.muted }}>from</span> {report.fixtureSource}
                </span>

                <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.04em' }}>Date</span>
                <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>{formatDate(report.timestamp)}</span>
              </div>
            </div>

            {/* Right: Score */}
            <div style={{
              display: 'flex', flexDirection: 'column', alignItems: 'center',
              padding: '16px 28px', borderRadius: 12,
              background: T.surface2, border: `1px solid ${T.border}`,
              minWidth: 180,
            }}>
              <div style={{ fontFamily: mono, fontSize: 10, color: T.muted, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 10 }}>
                Governance Score
              </div>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 10 }}>
                <span style={{ fontFamily: mono, fontSize: 32, fontWeight: 700, color: beforeColor, lineHeight: 1 }}>
                  {report.overallScore}
                </span>
                <span style={{ fontFamily: mono, fontSize: 16, color: T.dim }}>-&gt;</span>
                <span style={{ fontFamily: mono, fontSize: 32, fontWeight: 700, color: afterColor, lineHeight: 1 }}>
                  {report.afterScore}
                </span>
              </div>
              {delta > 0 && (
                <div style={{
                  fontFamily: mono, fontSize: 11, fontWeight: 600,
                  color: T.green, marginTop: 6,
                  background: T.greenDim, padding: '2px 10px', borderRadius: 4,
                }}>
                  +{delta} pts
                </div>
              )}
            </div>
          </div>

          {/* Summary pills */}
          <div style={{
            display: 'flex', gap: 10, marginTop: 24, flexWrap: 'wrap',
          }}>
            <div style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.green, background: T.greenDim,
              padding: '6px 14px', borderRadius: 6,
              border: `1px solid ${T.green}33`,
            }}>
              {report.autoFixedCount} auto-fixed
            </div>
            <div style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.amber, background: T.amberDim,
              padding: '6px 14px', borderRadius: 6,
              border: `1px solid ${T.amber}33`,
            }}>
              {report.warningCount} warnings
            </div>
            <div style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.red, background: T.redDim,
              padding: '6px 14px', borderRadius: 6,
              border: `1px solid ${T.red}33`,
            }}>
              {report.blockedCount} blocked
            </div>
            <div style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.blue, background: T.blueDim,
              padding: '6px 14px', borderRadius: 6,
              border: `1px solid ${T.blue}33`,
            }}>
              {report.violations.length} total issues
            </div>
          </div>
        </div>

        {/* ─── Category Breakdown ─────────────────────────── */}
        <div style={{
          background: T.surface, border: `1px solid ${T.border}`,
          borderRadius: 14, padding: '24px 32px', marginBottom: 24,
        }}>
          <div style={{
            fontFamily: sans, fontSize: 14, fontWeight: 700,
            color: T.textBright, marginBottom: 18,
            letterSpacing: '0.02em',
          }}>
            Category Scores
          </div>

          {report.categories.map(c => {
            const col = scoreColor(c.score)
            return (
              <div key={c.key} style={{
                display: 'flex', alignItems: 'center', gap: 12,
                marginBottom: 12,
              }}>
                <span style={{
                  fontFamily: sans, fontSize: 12, color: T.muted,
                  width: 130, flexShrink: 0,
                }}>
                  {c.name}
                </span>
                <div style={{
                  flex: 1, height: 6, borderRadius: 4,
                  background: T.border,
                  overflow: 'hidden',
                }}>
                  <div style={{
                    height: '100%', borderRadius: 4,
                    width: `${c.score}%`,
                    background: col,
                    transition: 'width 0.8s ease',
                  }} />
                </div>
                <span style={{
                  fontFamily: mono, fontSize: 12, fontWeight: 700,
                  color: col, width: 30, textAlign: 'right',
                  flexShrink: 0,
                }}>
                  {c.score}
                </span>
              </div>
            )
          })}
        </div>

        {/* ─── Auto-Fixed Section ─────────────────────────── */}
        {autoFixed.length > 0 && (
          <div>
            <SectionHeader label="AUTO-FIXED" count={autoFixed.length} color={T.green} dimColor={T.greenDim} />
            {autoFixed.map((v, i) => (
              <ViolationCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Warnings Section ───────────────────────────── */}
        {warnings.length > 0 && (
          <div>
            <SectionHeader label="WARNINGS" count={warnings.length} color={T.amber} dimColor={T.amberDim} />
            {warnings.map((v, i) => (
              <ViolationCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Blocked Section ────────────────────────────── */}
        {blocked.length > 0 && (
          <div>
            <SectionHeader label="BLOCKED" count={blocked.length} color={T.red} dimColor={T.redDim} />
            {blocked.map((v, i) => (
              <ViolationCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Action Buttons ─────────────────────────────── */}
        <div style={{
          display: 'flex', gap: 10, marginTop: 40, flexWrap: 'wrap',
          padding: '24px 0',
          borderTop: `1px solid ${T.border}`,
        }}>
          <CopyButton
            label="Copy as JSON"
            onCopy={() => navigator.clipboard.writeText(reportToJSON(report))}
          />
          <CopyButton
            label="Copy as Markdown"
            onCopy={() => navigator.clipboard.writeText(reportToMarkdown(report, company))}
          />
          <CopyButton
            label="Share Link"
            onCopy={() => navigator.clipboard.writeText(window.location.href)}
          />
        </div>

        {/* ─── CTA: MCP Integration ──────────────────────── */}
        <a href="/integrate" style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '20px 28px', marginTop: 24,
          background: T.surface, border: `1px solid ${T.border}`,
          borderRadius: 14, textDecoration: 'none',
          transition: 'border-color 0.2s',
        }}>
          <div>
            <div style={{
              fontFamily: sans, fontSize: 15, fontWeight: 700,
              color: T.textBright, marginBottom: 4,
            }}>
              Set up MCP integration
            </div>
            <div style={{
              fontFamily: sans, fontSize: 12, color: T.muted,
            }}>
              Enforce governance automatically in your AI coding workflow.
            </div>
          </div>
          <span style={{
            fontFamily: mono, fontSize: 18, color: T.green,
            flexShrink: 0, marginLeft: 16,
          }}>
            &rarr;
          </span>
        </a>

      </div>
    </div>
  )
}
