'use client'

import { useState, useEffect } from 'react'
import Stepper from '@/components/Stepper'
import { loadReport, loadSession, markStepComplete } from '@/lib/session'
import { reportToJSON, type GovernanceReport, type EnrichedViolation } from '@/lib/governance'

// ─── Design Tokens ──────────────────────────────────────────
const T = {
  bg: '#08090d', surface: '#0c0e12', surface2: '#111318',
  border: '#1a1d24', border2: '#252830',
  green: '#00e087', greenDim: '#00e08718',
  red: '#ff4070', redDim: '#ff407018',
  amber: '#ffb830', amberDim: '#ffb83018',
  blue: '#4090ff', blueDim: '#4090ff18',
  purple: '#a855f7', purpleDim: '#a855f718',
  muted: '#6b7280', dim: '#3a3f4a',
  text: '#e8eaf0', textBright: '#f8f9fb',
}
const mono = "'JetBrains Mono', 'DM Mono', monospace"
const syne = "'Syne', sans-serif"
const sans = "'DM Sans', system-ui, sans-serif"

// ─── Helpers ────────────────────────────────────────────────

function scoreColor(score: number): string {
  if (score >= 90) return T.green
  if (score >= 60) return T.amber
  return T.red
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })
  } catch { return iso }
}

function reportToMarkdown(report: GovernanceReport, company: string): string {
  const lines: string[] = []
  lines.push(`# Governance Report`)
  lines.push('')
  lines.push(`**Company:** ${company}`)
  lines.push(`**Design System:** Acme Design System`)
  lines.push(`**Scanned:** ${report.fixtureName} from ${report.fixtureSource}`)
  lines.push(`**Date:** ${formatDate(report.timestamp)}`)
  lines.push('')
  lines.push(`## Score: ${report.overallScore} → ${report.afterScore} (+${report.afterScore - report.overallScore})`)
  lines.push('')
  lines.push(`## Category Scores`)
  lines.push('')
  for (const c of report.categories) {
    const bar = '\u2588'.repeat(Math.round(c.score / 5)) + '\u2591'.repeat(20 - Math.round(c.score / 5))
    lines.push(`- **${c.name}**: ${c.score}/100  ${bar}`)
  }
  lines.push('')

  const autoFixed = report.violations.filter(v => v.fixApplied)
  const warnings = report.violations.filter(v => !v.fixApplied && v.severity === 'warn')
  const blocked = report.violations.filter(v => !v.fixApplied && v.severity === 'block')

  if (autoFixed.length > 0) {
    lines.push(`## Auto-Fixed (${autoFixed.length})`)
    lines.push('')
    for (const v of autoFixed) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.fixDescription}`)
    }
    lines.push('')
  }

  if (warnings.length > 0) {
    lines.push(`## Warnings (${warnings.length})`)
    lines.push('')
    for (const v of warnings) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.evidence}`)
      lines.push(`  _Recommended:_ ${v.fixDescription}`)
    }
    lines.push('')
  }

  if (blocked.length > 0) {
    lines.push(`## Blocked (${blocked.length})`)
    lines.push('')
    for (const v of blocked) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.evidence}`)
      lines.push(`  _Action required:_ ${v.fixDescription}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('Generated by [muteform](https://muteform.com)')
  return lines.join('\n')
}

// ─── Keyframes CSS ──────────────────────────────────────────

const keyframesCSS = `
@keyframes fadeInPage {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes fadeInCard {
  from { opacity: 0; transform: translateY(6px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes pulseFixed {
  0% { transform: scale(1); box-shadow: 0 0 0 0 ${T.green}44; }
  50% { transform: scale(1.08); box-shadow: 0 0 0 6px ${T.green}00; }
  100% { transform: scale(1); box-shadow: 0 0 0 0 ${T.green}00; }
}
@keyframes barGrow {
  from { width: 0%; }
}
@keyframes scoreGlow {
  0% { filter: drop-shadow(0 0 6px ${T.green}66); }
  50% { filter: drop-shadow(0 0 14px ${T.green}44); }
  100% { filter: drop-shadow(0 0 6px ${T.green}66); }
}
.report-btn:hover {
  transform: scale(1.02) !important;
}
`

// ─── ScoreRing ──────────────────────────────────────────────

function ScoreRing({ score, size = 120 }: { score: number; size?: number }) {
  const [animatedScore, setAnimatedScore] = useState(0)
  const [visible, setVisible] = useState(false)
  const strokeWidth = 8
  const radius = (size - strokeWidth) / 2
  const circumference = 2 * Math.PI * radius
  const color = scoreColor(score)

  useEffect(() => {
    if (!visible) return
    const duration = 1400
    const start = performance.now()
    let raf: number
    const animate = (now: number) => {
      const elapsed = now - start
      const progress = Math.min(elapsed / duration, 1)
      // ease-out cubic
      const eased = 1 - Math.pow(1 - progress, 3)
      setAnimatedScore(Math.round(eased * score))
      if (progress < 1) {
        raf = requestAnimationFrame(animate)
      }
    }
    raf = requestAnimationFrame(animate)
    return () => cancelAnimationFrame(raf)
  }, [visible, score])

  useEffect(() => {
    // Use IntersectionObserver to trigger on visibility
    const el = document.getElementById('score-ring-container')
    if (!el) { setVisible(true); return }
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.disconnect() } },
      { threshold: 0.3 }
    )
    obs.observe(el)
    return () => obs.disconnect()
  }, [])

  const offset = circumference - (circumference * (animatedScore / 100))

  return (
    <div
      id="score-ring-container"
      style={{
        position: 'relative', width: size, height: size,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        animation: visible ? 'scoreGlow 3s ease-in-out infinite' : 'none',
      }}
    >
      <svg width={size} height={size} style={{ transform: 'rotate(-90deg)' }}>
        {/* Track */}
        <circle
          cx={size / 2} cy={size / 2} r={radius}
          fill="none" stroke={T.border2} strokeWidth={strokeWidth}
        />
        {/* Score arc */}
        <circle
          cx={size / 2} cy={size / 2} r={radius}
          fill="none" stroke={color} strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          style={{ transition: 'stroke-dashoffset 0.05s linear' }}
        />
      </svg>
      {/* Center number */}
      <div style={{
        position: 'absolute', inset: 0,
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
      }}>
        <span style={{
          fontFamily: mono, fontSize: size * 0.3, fontWeight: 800,
          color, lineHeight: 1,
        }}>
          {animatedScore}
        </span>
        <span style={{
          fontFamily: mono, fontSize: 9, color: T.muted,
          letterSpacing: '0.08em', textTransform: 'uppercase', marginTop: 4,
        }}>
          / 100
        </span>
      </div>
    </div>
  )
}

// ─── ViolationPreview ───────────────────────────────────────

function ViolationPreview({ v }: { v: EnrichedViolation }) {
  if (v.type === 'color_token') {
    const hex = v.evidence.match(/#[0-9a-fA-F]{6}/)?.[0] || '#ff0000'
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ fontFamily: mono, fontSize: 10, color: T.muted }}>Was:</span>
          <div style={{
            width: 18, height: 18, borderRadius: '50%', background: hex,
            border: `2px solid ${T.red}88`, flexShrink: 0,
          }} />
          <span style={{ fontFamily: mono, fontSize: 10, color: T.red }}>{hex}</span>
        </div>
        {v.suggestedFix && v.suggestedFix.startsWith('#') && (
          <>
            <span style={{ fontFamily: mono, fontSize: 12, color: T.dim }}>{'\u2192'}</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ fontFamily: mono, fontSize: 10, color: T.muted }}>Now:</span>
              <div style={{
                width: 18, height: 18, borderRadius: '50%', background: v.suggestedFix,
                border: `2px solid ${T.green}88`, flexShrink: 0,
              }} />
              <span style={{ fontFamily: mono, fontSize: 10, color: T.green }}>{v.suggestedFix}</span>
            </div>
          </>
        )}
      </div>
    )
  }

  if (v.type === 'spacing') {
    const cur = parseInt(v.evidence.match(/(\d+)/)?.[1] || '10')
    const sug = parseInt(v.suggestedFix.match(/(\d+)/)?.[1] || String(cur))
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}>
        <span style={{ fontFamily: mono, fontSize: 10, color: T.muted }}>Was:</span>
        <div style={{
          width: Math.min(cur * 2, 60), height: 8, borderRadius: 4,
          background: `${T.red}80`,
        }} />
        <span style={{ fontFamily: mono, fontSize: 10, color: T.red }}>{cur}px</span>
        <span style={{ fontFamily: mono, fontSize: 12, color: T.dim }}>{'\u2192'}</span>
        <span style={{ fontFamily: mono, fontSize: 10, color: T.muted }}>Now:</span>
        <div style={{
          width: Math.min(sug * 2, 60), height: 8, borderRadius: 4,
          background: `${T.green}80`,
        }} />
        <span style={{ fontFamily: mono, fontSize: 10, color: T.green }}>{sug}px</span>
      </div>
    )
  }

  if (v.type === 'typography') {
    return (
      <div style={{
        fontFamily: mono, fontSize: 11, color: T.muted, marginTop: 6,
        display: 'flex', alignItems: 'center', gap: 6,
      }}>
        <span style={{
          padding: '2px 8px', borderRadius: 4,
          background: T.redDim, color: T.red,
          border: `1px solid ${T.red}22`, fontSize: 10,
        }}>
          {v.evidence.match(/"([^"]+)"/)?.[1] || v.evidence}
        </span>
        {v.suggestedFix && (
          <>
            <span style={{ color: T.dim }}>{'\u2192'}</span>
            <span style={{
              padding: '2px 8px', borderRadius: 4,
              background: T.greenDim, color: T.green,
              border: `1px solid ${T.green}22`, fontSize: 10,
            }}>
              {v.suggestedFix}
            </span>
          </>
        )}
      </div>
    )
  }

  if (v.type === 'component') {
    return (
      <div style={{
        display: 'flex', alignItems: 'center', gap: 6, marginTop: 6,
      }}>
        <span style={{
          fontFamily: mono, fontSize: 10, padding: '2px 10px',
          borderRadius: 12, background: T.redDim, color: T.red,
          border: `1px solid ${T.red}22`,
        }}>
          {v.evidence.match(/"([^"]+)"/)?.[1] || 'unknown'}
        </span>
        {v.suggestedFix && (
          <>
            <span style={{ fontFamily: mono, fontSize: 10, color: T.dim }}>{'\u2192'}</span>
            <span style={{
              fontFamily: mono, fontSize: 10, padding: '2px 10px',
              borderRadius: 12, background: T.greenDim, color: T.green,
              border: `1px solid ${T.green}22`,
            }}>
              {v.suggestedFix}
            </span>
          </>
        )}
      </div>
    )
  }

  return (
    <div style={{ fontFamily: sans, fontSize: 11, color: T.muted, marginTop: 6 }}>
      {v.fixDescription}
    </div>
  )
}

// ─── SectionHeader ──────────────────────────────────────────

function SectionHeader({ label, count, color, dimColor }: {
  label: string; count: number; color: string; dimColor: string
}) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 10,
      padding: '14px 0', marginTop: 32,
      borderBottom: `1px solid ${T.border}`,
    }}>
      <span style={{
        fontFamily: mono, fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
        color, background: dimColor,
        padding: '3px 10px', borderRadius: 4,
        border: `1px solid ${color}33`,
      }}>
        {label}
      </span>
      <span style={{ fontFamily: mono, fontSize: 13, fontWeight: 700, color }}>{count}</span>
      <div style={{ flex: 1, height: 1, background: T.border }} />
    </div>
  )
}

// ─── AutoFixed Card ─────────────────────────────────────────

function AutoFixedCard({ v, index }: { v: EnrichedViolation; index: number }) {
  return (
    <div style={{
      padding: '16px 20px', background: T.surface,
      border: `1px solid ${T.green}18`,
      borderRadius: 10, marginTop: 8,
      borderLeft: `3px solid ${T.green}44`,
      animation: `fadeInCard 0.4s ease ${index * 50}ms both`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: sans, fontSize: 13, fontWeight: 700,
            color: T.textBright, lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: mono, fontSize: 10, color: T.dim,
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: mono, fontSize: 9, fontWeight: 700, letterSpacing: '0.08em',
          color: T.green, background: T.greenDim,
          padding: '3px 10px', borderRadius: 4,
          border: `1px solid ${T.green}33`,
          whiteSpace: 'nowrap', flexShrink: 0,
          animation: 'pulseFixed 0.6s ease 0.5s both',
        }}>
          FIXED
        </span>
      </div>

      <ViolationPreview v={v} />
    </div>
  )
}

// ─── Warning Card ───────────────────────────────────────────

function WarningCard({ v, index }: { v: EnrichedViolation; index: number }) {
  return (
    <div style={{
      padding: '16px 20px', background: T.surface,
      border: `1px solid ${T.amber}18`,
      borderRadius: 10, marginTop: 8,
      borderLeft: `3px solid ${T.amber}44`,
      animation: `fadeInCard 0.4s ease ${index * 50}ms both`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: sans, fontSize: 13, fontWeight: 700,
            color: T.textBright, lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: mono, fontSize: 10, color: T.dim,
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: mono, fontSize: 9, fontWeight: 700, letterSpacing: '0.08em',
          color: T.amber, background: T.amberDim,
          padding: '3px 10px', borderRadius: 4,
          border: `1px solid ${T.amber}33`,
          whiteSpace: 'nowrap', flexShrink: 0,
        }}>
          WARNING
        </span>
      </div>

      <div style={{
        fontFamily: sans, fontSize: 12, color: T.muted,
        marginTop: 10, lineHeight: 1.6,
      }}>
        <span style={{ color: T.text, fontWeight: 600 }}>Found: </span>{v.evidence}
      </div>
      <div style={{
        fontFamily: sans, fontSize: 12, color: T.muted,
        marginTop: 4, lineHeight: 1.6,
      }}>
        <span style={{ color: T.amber, fontWeight: 600 }}>Recommended: </span>{v.fixDescription}
      </div>
    </div>
  )
}

// ─── Blocked Card ───────────────────────────────────────────

function BlockedCard({ v, index }: { v: EnrichedViolation; index: number }) {
  return (
    <div style={{
      padding: '16px 20px', background: T.surface,
      border: `1px solid ${T.red}18`,
      borderRadius: 10, marginTop: 8,
      borderLeft: `3px solid ${T.red}44`,
      animation: `fadeInCard 0.4s ease ${index * 50}ms both`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: sans, fontSize: 13, fontWeight: 700,
            color: T.textBright, lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: mono, fontSize: 10, color: T.dim,
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: mono, fontSize: 9, fontWeight: 700, letterSpacing: '0.08em',
          color: T.red, background: T.redDim,
          padding: '3px 10px', borderRadius: 4,
          border: `1px solid ${T.red}33`,
          whiteSpace: 'nowrap', flexShrink: 0,
        }}>
          BLOCKED
        </span>
      </div>

      <div style={{
        fontFamily: sans, fontSize: 12, color: T.muted,
        marginTop: 10, lineHeight: 1.6,
      }}>
        <span style={{ color: T.text, fontWeight: 600 }}>Issue: </span>{v.evidence}
      </div>
      <div style={{
        fontFamily: sans, fontSize: 12, color: T.muted,
        marginTop: 4, lineHeight: 1.6,
      }}>
        <span style={{ color: T.red, fontWeight: 600 }}>Action required: </span>{v.fixDescription}
      </div>
    </div>
  )
}

// ─── CopyButton ─────────────────────────────────────────────

function CopyButton({ label, onCopy }: { label: string; onCopy: () => void }) {
  const [copied, setCopied] = useState(false)

  const handleClick = () => {
    onCopy()
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button
      className="report-btn"
      onClick={handleClick}
      style={{
        fontFamily: mono, fontSize: 11, fontWeight: 600,
        padding: '10px 20px', borderRadius: 8, cursor: 'pointer',
        background: copied ? T.greenDim : T.surface,
        color: copied ? T.green : T.textBright,
        border: `1px solid ${copied ? T.green + '44' : T.border}`,
        letterSpacing: '0.04em',
        transition: 'all 150ms ease',
      }}
    >
      {copied ? 'Copied!' : label}
    </button>
  )
}

// ─── CategoryBar ────────────────────────────────────────────

function CategoryBar({ name, score, delay }: { name: string; score: number; delay: number }) {
  const color = scoreColor(score)
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 12,
      marginBottom: 14,
    }}>
      <span style={{
        fontFamily: sans, fontSize: 12, color: T.muted,
        width: 140, flexShrink: 0,
      }}>
        {name}
      </span>
      <div style={{
        flex: 1, height: 8, borderRadius: 4,
        background: T.border,
        overflow: 'hidden',
      }}>
        <div style={{
          height: '100%', borderRadius: 4,
          width: `${score}%`,
          background: `linear-gradient(90deg, ${color}cc, ${color})`,
          animation: `barGrow 0.8s ease ${delay}ms both`,
        }} />
      </div>
      <span style={{
        fontFamily: mono, fontSize: 12, fontWeight: 700,
        color, width: 32, textAlign: 'right',
        flexShrink: 0,
      }}>
        {score}
      </span>
    </div>
  )
}

// ─── Main Page ──────────────────────────────────────────────

export default function ReportPage() {
  const [report, setReport] = useState<GovernanceReport | null>(null)
  const [company, setCompany] = useState('')
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    const r = loadReport() as GovernanceReport | null
    const session = loadSession()
    setReport(r)
    setCompany(session.user?.company || 'Your Company')
    setLoaded(true)
    markStepComplete(3)
  }, [])

  if (!loaded) return null

  // ─── Empty State ────────────────────────────────────────
  if (!report) {
    return (
      <div style={{ minHeight: '100vh', background: T.bg, color: T.text }}>
        <style>{keyframesCSS}</style>
        <Stepper />
        <div style={{
          maxWidth: 900, margin: '0 auto', padding: '120px 20px',
          textAlign: 'center',
          animation: 'fadeInPage 0.5s ease both',
        }}>
          <div style={{
            fontFamily: sans, fontSize: 20, fontWeight: 700,
            color: T.textBright, marginBottom: 8,
          }}>
            No report yet.
          </div>
          <div style={{
            fontFamily: sans, fontSize: 14, color: T.muted, marginBottom: 28,
          }}>
            Run a governance scan first.
          </div>
          <a
            href="/scan"
            className="report-btn"
            style={{
              fontFamily: mono, fontSize: 13, fontWeight: 700,
              color: '#000', background: T.green,
              textDecoration: 'none',
              padding: '12px 32px', borderRadius: 8,
              border: 'none',
              display: 'inline-block',
              letterSpacing: '0.02em',
              transition: 'all 150ms ease',
            }}
          >
            Go to Scan {'\u2192'}
          </a>
        </div>
      </div>
    )
  }

  // ─── Report Data ────────────────────────────────────────
  const autoFixed = report.violations.filter(v => v.fixApplied)
  const warnings = report.violations.filter(v => !v.fixApplied && v.severity === 'warn')
  const blocked = report.violations.filter(v => !v.fixApplied && v.severity === 'block')
  const delta = report.afterScore - report.overallScore

  return (
    <div style={{ minHeight: '100vh', background: T.bg, color: T.text }}>
      <style>{keyframesCSS}</style>
      <Stepper />

      <div style={{
        maxWidth: 900, margin: '0 auto', padding: '32px 20px 120px',
        animation: 'fadeInPage 0.5s ease both',
      }}>

        {/* ─── Header ──────────────────────────────────────── */}
        <div style={{
          background: T.surface, border: `1px solid ${T.border}`,
          borderRadius: 14, padding: '32px 36px', marginBottom: 24,
        }}>
          <div style={{
            fontFamily: syne, fontSize: 24, fontWeight: 800,
            color: T.textBright, marginBottom: 20,
          }}>
            Muteform Governance Report
          </div>

          <div style={{
            display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px 20px',
          }}>
            <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.06em' }}>Company</span>
            <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>{company}</span>

            <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.06em' }}>Design System</span>
            <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>Acme Design System</span>

            <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.06em' }}>Scanned</span>
            <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>
              {report.fixtureName} <span style={{ color: T.muted }}>from</span> {report.fixtureSource}
            </span>

            <span style={{ fontFamily: mono, fontSize: 11, color: T.dim, letterSpacing: '0.06em' }}>Date</span>
            <span style={{ fontFamily: sans, fontSize: 13, color: T.text }}>{formatDate(report.timestamp)}</span>
          </div>
        </div>

        {/* ─── Score Card ──────────────────────────────────── */}
        <div style={{
          background: T.surface, border: `1px solid ${T.border}`,
          borderRadius: 14, padding: '36px 36px 28px',
          marginBottom: 24,
          display: 'flex', flexDirection: 'column', alignItems: 'center',
        }}>
          <ScoreRing score={report.afterScore} size={120} />

          <div style={{
            fontFamily: mono, fontSize: 13, color: T.muted,
            marginTop: 16, textAlign: 'center', lineHeight: 1.6,
          }}>
            <span style={{ color: scoreColor(report.overallScore), fontWeight: 700 }}>{report.overallScore}</span>
            <span style={{ color: T.dim, margin: '0 8px' }}>{'\u2192'}</span>
            <span style={{ color: scoreColor(report.afterScore), fontWeight: 700 }}>{report.afterScore}</span>
            <span style={{ color: T.dim, margin: '0 6px' }}>{'\u00B7'}</span>
            {delta > 0 ? (
              <span style={{
                color: T.green, fontWeight: 700,
                background: T.greenDim, padding: '2px 10px', borderRadius: 4,
                border: `1px solid ${T.green}33`,
              }}>
                +{delta} points after governance
              </span>
            ) : (
              <span style={{ color: T.muted }}>
                {delta === 0 ? 'no change' : `${delta} points`}
              </span>
            )}
          </div>

          {/* Summary pills */}
          <div style={{
            display: 'flex', gap: 10, marginTop: 20, flexWrap: 'wrap', justifyContent: 'center',
          }}>
            <span style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.green, background: T.greenDim,
              padding: '5px 14px', borderRadius: 6,
              border: `1px solid ${T.green}33`,
            }}>
              {report.autoFixedCount} auto-fixed
            </span>
            <span style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.amber, background: T.amberDim,
              padding: '5px 14px', borderRadius: 6,
              border: `1px solid ${T.amber}33`,
            }}>
              {report.warningCount} warnings
            </span>
            <span style={{
              fontFamily: mono, fontSize: 11, fontWeight: 600,
              color: T.red, background: T.redDim,
              padding: '5px 14px', borderRadius: 6,
              border: `1px solid ${T.red}33`,
            }}>
              {report.blockedCount} blocked
            </span>
          </div>
        </div>

        {/* ─── Category Breakdown ──────────────────────────── */}
        <div style={{
          background: T.surface, border: `1px solid ${T.border}`,
          borderRadius: 14, padding: '28px 36px', marginBottom: 24,
        }}>
          <div style={{
            fontFamily: sans, fontSize: 14, fontWeight: 700,
            color: T.textBright, marginBottom: 20,
            letterSpacing: '0.02em',
          }}>
            Category Breakdown
          </div>

          {report.categories.map((c, i) => (
            <CategoryBar key={c.key} name={c.name} score={c.score} delay={200 + i * 100} />
          ))}
        </div>

        {/* ─── Auto-Fixed Section ──────────────────────────── */}
        {autoFixed.length > 0 && (
          <div>
            <SectionHeader label="AUTO-FIXED" count={autoFixed.length} color={T.green} dimColor={T.greenDim} />
            {autoFixed.map((v, i) => (
              <AutoFixedCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Warnings Section ────────────────────────────── */}
        {warnings.length > 0 && (
          <div>
            <SectionHeader label="WARNINGS" count={warnings.length} color={T.amber} dimColor={T.amberDim} />
            {warnings.map((v, i) => (
              <WarningCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Blocked Section ─────────────────────────────── */}
        {blocked.length > 0 && (
          <div>
            <SectionHeader label="BLOCKED" count={blocked.length} color={T.red} dimColor={T.redDim} />
            {blocked.map((v, i) => (
              <BlockedCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Bottom Action Bar ───────────────────────────── */}
        <div style={{
          display: 'flex', gap: 10, marginTop: 48, flexWrap: 'wrap',
          padding: '24px 0',
          borderTop: `1px solid ${T.border}`,
          position: 'sticky', bottom: 0,
          background: T.bg,
          zIndex: 10,
        }}>
          <CopyButton
            label="Copy as JSON"
            onCopy={() => navigator.clipboard.writeText(reportToJSON(report))}
          />
          <CopyButton
            label="Copy as Markdown"
            onCopy={() => navigator.clipboard.writeText(reportToMarkdown(report, company))}
          />
          <CopyButton
            label="Share Report"
            onCopy={() => navigator.clipboard.writeText(window.location.href)}
          />
          <div style={{ flex: 1 }} />
          <a
            href="/scan"
            className="report-btn"
            style={{
              fontFamily: mono, fontSize: 11, fontWeight: 700,
              padding: '10px 24px', borderRadius: 8, cursor: 'pointer',
              background: T.green, color: '#000',
              border: 'none', textDecoration: 'none',
              letterSpacing: '0.02em',
              display: 'inline-flex', alignItems: 'center', gap: 6,
              transition: 'all 150ms ease',
            }}
          >
            Scan another {'\u2192'}
          </a>
        </div>

        {/* ─── CTA: MCP Integration ────────────────────────── */}
        <a
          href="/integrate"
          className="report-btn"
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '24px 32px', marginTop: 24,
            background: T.surface, border: `1px solid ${T.border}`,
            borderRadius: 14, textDecoration: 'none',
            transition: 'all 150ms ease',
          }}
        >
          <div>
            <div style={{
              fontFamily: sans, fontSize: 16, fontWeight: 700,
              color: T.textBright, marginBottom: 6,
            }}>
              Set up MCP integration
            </div>
            <div style={{
              fontFamily: sans, fontSize: 13, color: T.muted, lineHeight: 1.5,
            }}>
              Enforce governance automatically in your AI coding workflow.
            </div>
          </div>
          <span style={{
            fontFamily: mono, fontSize: 22, color: T.green,
            flexShrink: 0, marginLeft: 20,
          }}>
            {'\u2192'}
          </span>
        </a>

      </div>
    </div>
  )
}
