'use client'

export const dynamic = 'force-dynamic'

import { useState, useEffect } from 'react'
import Header from '@/components/Header'
import { loadReport, loadSession, markStepComplete } from '@/lib/session'
import { reportToJSON, type GovernanceReport, type EnrichedViolation } from '@/lib/governance'

// ─── Helpers ────────────────────────────────────────────────

function scoreColor(score: number): string {
  if (score >= 90) return 'var(--success)'
  if (score >= 60) return 'var(--warning)'
  return 'var(--error)'
}

function scoreColorDim(score: number): string {
  if (score >= 90) return 'var(--success-dim)'
  if (score >= 60) return 'var(--warning-dim)'
  return 'var(--error-dim)'
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })
  } catch { return iso }
}

function reportToMarkdown(report: GovernanceReport, company: string): string {
  const lines: string[] = []
  lines.push(`# Governance Report`)
  lines.push('')
  lines.push(`**Company:** ${company}`)
  lines.push(`**Design System:** Acme Design System`)
  lines.push(`**Scanned:** ${report.fixtureName} from ${report.fixtureSource}`)
  lines.push(`**Date:** ${formatDate(report.timestamp)}`)
  lines.push('')
  lines.push(`## Score: ${report.overallScore} \u2192 ${report.afterScore} (+${report.afterScore - report.overallScore})`)
  lines.push('')
  lines.push(`## Category Scores`)
  lines.push('')
  for (const c of report.categories) {
    const bar = '\u2588'.repeat(Math.round(c.score / 5)) + '\u2591'.repeat(20 - Math.round(c.score / 5))
    lines.push(`- **${c.name}**: ${c.score}/100  ${bar}`)
  }
  lines.push('')

  const autoFixed = report.violations.filter(v => v.fixApplied)
  const warnings = report.violations.filter(v => !v.fixApplied && v.severity === 'warn')
  const blocked = report.violations.filter(v => !v.fixApplied && v.severity === 'block')

  if (autoFixed.length > 0) {
    lines.push(`## Auto-Fixed (${autoFixed.length})`)
    lines.push('')
    for (const v of autoFixed) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.fixDescription}`)
    }
    lines.push('')
  }

  if (warnings.length > 0) {
    lines.push(`## Warnings (${warnings.length})`)
    lines.push('')
    for (const v of warnings) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.evidence}`)
      lines.push(`  _Recommended:_ ${v.fixDescription}`)
    }
    lines.push('')
  }

  if (blocked.length > 0) {
    lines.push(`## Blocked (${blocked.length})`)
    lines.push('')
    for (const v of blocked) {
      lines.push(`- **${v.ruleName}** @ \`${v.nodePath}\``)
      lines.push(`  ${v.evidence}`)
      lines.push(`  _Action required:_ ${v.fixDescription}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('Generated by [muteform](https://muteform.com)')
  return lines.join('\n')
}

// ─── Keyframes CSS ──────────────────────────────────────────

const keyframesCSS = `
@keyframes fadeInPage {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes fadeInCard {
  from { opacity: 0; transform: translateY(6px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes pulseFixed {
  0% { transform: scale(1); }
  50% { transform: scale(1.08); }
  100% { transform: scale(1); }
}
@keyframes barGrow {
  from { width: 0%; }
}
@keyframes scoreGlow {
  0% { opacity: 1; }
  50% { opacity: 0.85; }
  100% { opacity: 1; }
}
.report-btn:hover {
  transform: scale(1.02) !important;
}
`

// ─── ScoreRing ──────────────────────────────────────────────

function ScoreRing({ score, size = 120 }: { score: number; size?: number }) {
  const [animatedScore, setAnimatedScore] = useState(0)
  const [visible, setVisible] = useState(false)
  const strokeWidth = 8
  const radius = (size - strokeWidth) / 2
  const circumference = 2 * Math.PI * radius

  useEffect(() => {
    if (!visible) return
    const duration = 1400
    const start = performance.now()
    let raf: number
    const animate = (now: number) => {
      const elapsed = now - start
      const progress = Math.min(elapsed / duration, 1)
      const eased = 1 - Math.pow(1 - progress, 3)
      setAnimatedScore(Math.round(eased * score))
      if (progress < 1) {
        raf = requestAnimationFrame(animate)
      }
    }
    raf = requestAnimationFrame(animate)
    return () => cancelAnimationFrame(raf)
  }, [visible, score])

  useEffect(() => {
    const el = document.getElementById('score-ring-container')
    if (!el) { setVisible(true); return }
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.disconnect() } },
      { threshold: 0.3 }
    )
    obs.observe(el)
    return () => obs.disconnect()
  }, [])

  const offset = circumference - (circumference * (animatedScore / 100))

  return (
    <div
      id="score-ring-container"
      style={{
        position: 'relative', width: size, height: size,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        animation: visible ? 'scoreGlow 3s ease-in-out infinite' : 'none',
      }}
    >
      <svg width={size} height={size} style={{ transform: 'rotate(-90deg)' }}>
        {/* Track */}
        <circle
          cx={size / 2} cy={size / 2} r={radius}
          fill="none" stroke="var(--border)" strokeWidth={strokeWidth}
        />
        {/* Score arc */}
        <circle
          cx={size / 2} cy={size / 2} r={radius}
          fill="none" stroke={scoreColor(score)} strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          style={{ transition: 'stroke-dashoffset 0.05s linear' }}
        />
      </svg>
      {/* Center number */}
      <div style={{
        position: 'absolute', inset: 0,
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
      }}>
        <span style={{
          fontFamily: 'var(--font-heading)', fontSize: size * 0.3, fontWeight: 800,
          color: scoreColor(score), lineHeight: 1,
        }}>
          {animatedScore}
        </span>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 9, color: 'var(--text-muted)',
          letterSpacing: '0.08em', textTransform: 'uppercase', marginTop: 4,
        }}>
          / 100
        </span>
      </div>
    </div>
  )
}

// ─── ViolationPreview ───────────────────────────────────────

function ViolationPreview({ v }: { v: EnrichedViolation }) {
  if (v.type === 'color_token') {
    const hex = v.evidence.match(/#[0-9a-fA-F]{6}/)?.[0] || '#ff0000'
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)' }}>Was:</span>
          <div style={{
            width: 14, height: 14, borderRadius: '50%', background: hex,
            border: '2px solid var(--error)', flexShrink: 0,
          }} />
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--error)' }}>{hex}</span>
        </div>
        {v.suggestedFix && v.suggestedFix.startsWith('#') && (
          <>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)' }}>{'\u2192'}</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)' }}>Now:</span>
              <div style={{
                width: 14, height: 14, borderRadius: '50%', background: v.suggestedFix,
                border: '2px solid var(--success)', flexShrink: 0,
              }} />
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--success)' }}>{v.suggestedFix}</span>
            </div>
          </>
        )}
      </div>
    )
  }

  if (v.type === 'spacing') {
    const cur = parseInt(v.evidence.match(/(\d+)/)?.[1] || '10')
    const sug = parseInt(v.suggestedFix.match(/(\d+)/)?.[1] || String(cur))
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)' }}>Was:</span>
        <div style={{
          width: Math.min(cur * 2, 60), height: 8, borderRadius: 4,
          background: 'var(--error)',
          opacity: 0.5,
        }} />
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--error)' }}>{cur}px</span>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)' }}>{'\u2192'}</span>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)' }}>Now:</span>
        <div style={{
          width: Math.min(sug * 2, 60), height: 8, borderRadius: 4,
          background: 'var(--success)',
          opacity: 0.5,
        }} />
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--success)' }}>{sug}px</span>
      </div>
    )
  }

  if (v.type === 'typography') {
    return (
      <div style={{
        fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', marginTop: 6,
        display: 'flex', alignItems: 'center', gap: 6,
      }}>
        <span style={{
          padding: '2px 8px', borderRadius: 4,
          background: 'var(--error-dim)', color: 'var(--error)',
          border: '1px solid var(--error)', fontSize: 10,
          borderColor: 'color-mix(in srgb, var(--error) 20%, transparent)',
        }}>
          {v.evidence.match(/"([^"]+)"/)?.[1] || v.evidence}
        </span>
        {v.suggestedFix && (
          <>
            <span style={{ color: 'var(--text-muted)' }}>{'\u2192'}</span>
            <span style={{
              padding: '2px 8px', borderRadius: 4,
              background: 'var(--success-dim)', color: 'var(--success)',
              border: '1px solid var(--success)', fontSize: 10,
              borderColor: 'color-mix(in srgb, var(--success) 20%, transparent)',
            }}>
              {v.suggestedFix}
            </span>
          </>
        )}
      </div>
    )
  }

  if (v.type === 'component') {
    return (
      <div style={{
        display: 'flex', alignItems: 'center', gap: 6, marginTop: 6,
      }}>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 10, padding: '2px 10px',
          borderRadius: 12, background: 'var(--error-dim)', color: 'var(--error)',
          border: '1px solid var(--error)',
          borderColor: 'color-mix(in srgb, var(--error) 20%, transparent)',
        }}>
          {v.evidence.match(/"([^"]+)"/)?.[1] || 'unknown'}
        </span>
        {v.suggestedFix && (
          <>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)' }}>{'\u2192'}</span>
            <span style={{
              fontFamily: 'var(--font-mono)', fontSize: 10, padding: '2px 10px',
              borderRadius: 12, background: 'var(--success-dim)', color: 'var(--success)',
              border: '1px solid var(--success)',
              borderColor: 'color-mix(in srgb, var(--success) 20%, transparent)',
            }}>
              {v.suggestedFix}
            </span>
          </>
        )}
      </div>
    )
  }

  return (
    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', marginTop: 6 }}>
      {v.fixDescription}
    </div>
  )
}

// ─── SectionHeader ──────────────────────────────────────────

function SectionHeader({ label, count, color, dimColor }: {
  label: string; count: number; color: string; dimColor: string
}) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 10,
      padding: '14px 0', marginTop: 32,
      borderBottom: '1px solid var(--border)',
    }}>
      <span style={{
        fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
        color, background: dimColor,
        padding: '3px 10px', borderRadius: 4,
        border: `1px solid ${color}`,
        borderColor: 'color-mix(in srgb, currentColor 25%, transparent)',
      }}>
        {label}
      </span>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700, color }}>{count}</span>
      <div style={{ flex: 1, height: 1, background: 'var(--border)' }} />
    </div>
  )
}

// ─── AutoFixed Card ─────────────────────────────────────────

function AutoFixedCard({ v, index }: { v: EnrichedViolation; index: number }) {
  return (
    <div style={{
      padding: '16px 20px', background: 'var(--surface)',
      border: '1px solid var(--border)',
      borderRadius: 4, marginTop: 8,
      borderLeft: '3px solid var(--success)',
      animation: `fadeInCard 0.4s ease ${index * 50}ms both`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700,
            color: 'var(--text-primary)', lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)',
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 9, fontWeight: 700, letterSpacing: '0.08em',
          color: 'var(--success)', background: 'var(--success-dim)',
          padding: '3px 10px', borderRadius: 4,
          border: '1px solid color-mix(in srgb, var(--success) 25%, transparent)',
          whiteSpace: 'nowrap', flexShrink: 0,
          animation: 'pulseFixed 0.6s ease 0.5s both',
        }}>
          FIXED
        </span>
      </div>

      <ViolationPreview v={v} />
    </div>
  )
}

// ─── Warning Card ───────────────────────────────────────────

function WarningCard({ v, index }: { v: EnrichedViolation; index: number }) {
  return (
    <div style={{
      padding: '16px 20px', background: 'var(--surface)',
      border: '1px solid var(--border)',
      borderRadius: 4, marginTop: 8,
      borderLeft: '3px solid var(--warning)',
      animation: `fadeInCard 0.4s ease ${index * 50}ms both`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700,
            color: 'var(--text-primary)', lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)',
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 9, fontWeight: 700, letterSpacing: '0.08em',
          color: 'var(--warning)', background: 'var(--warning-dim)',
          padding: '3px 10px', borderRadius: 4,
          border: '1px solid color-mix(in srgb, var(--warning) 25%, transparent)',
          whiteSpace: 'nowrap', flexShrink: 0,
        }}>
          WARNING
        </span>
      </div>

      <div style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)',
        marginTop: 10, lineHeight: 1.6,
      }}>
        <span style={{ color: 'var(--text-secondary)', fontWeight: 600 }}>Found: </span>{v.evidence}
      </div>
      <div style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)',
        marginTop: 4, lineHeight: 1.6,
      }}>
        <span style={{ color: 'var(--warning)', fontWeight: 600 }}>Recommended: </span>{v.fixDescription}
      </div>
    </div>
  )
}

// ─── Blocked Card ───────────────────────────────────────────

function BlockedCard({ v, index }: { v: EnrichedViolation; index: number }) {
  return (
    <div style={{
      padding: '16px 20px', background: 'var(--surface)',
      border: '1px solid var(--border)',
      borderRadius: 4, marginTop: 8,
      borderLeft: '3px solid var(--error)',
      animation: `fadeInCard 0.4s ease ${index * 50}ms both`,
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ flex: 1 }}>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700,
            color: 'var(--text-primary)', lineHeight: 1.3,
          }}>
            {v.ruleName}
          </div>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-muted)',
            marginTop: 4, wordBreak: 'break-all',
          }}>
            {v.nodePath}
          </div>
        </div>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 9, fontWeight: 700, letterSpacing: '0.08em',
          color: 'var(--error)', background: 'var(--error-dim)',
          padding: '3px 10px', borderRadius: 4,
          border: '1px solid color-mix(in srgb, var(--error) 25%, transparent)',
          whiteSpace: 'nowrap', flexShrink: 0,
        }}>
          BLOCKED
        </span>
      </div>

      <div style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)',
        marginTop: 10, lineHeight: 1.6,
      }}>
        <span style={{ color: 'var(--text-secondary)', fontWeight: 600 }}>Issue: </span>{v.evidence}
      </div>
      <div style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)',
        marginTop: 4, lineHeight: 1.6,
      }}>
        <span style={{ color: 'var(--error)', fontWeight: 600 }}>Action required: </span>{v.fixDescription}
      </div>
    </div>
  )
}

// ─── CopyButton ─────────────────────────────────────────────

function CopyButton({ label, onCopy }: { label: string; onCopy: () => void }) {
  const [copied, setCopied] = useState(false)

  const handleClick = () => {
    onCopy()
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button
      className="report-btn"
      onClick={handleClick}
      style={{
        fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
        padding: '10px 20px', borderRadius: 4, cursor: 'pointer',
        background: copied ? 'var(--success-dim)' : 'var(--surface)',
        color: copied ? 'var(--success)' : 'var(--text-primary)',
        border: copied ? '1px solid var(--success)' : '1px solid var(--border)',
        letterSpacing: '0.04em',
        transition: 'all 150ms ease',
      }}
    >
      {copied ? 'Copied!' : label}
    </button>
  )
}

// ─── CategoryBar ────────────────────────────────────────────

function CategoryBar({ name, score, delay }: { name: string; score: number; delay: number }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 12,
      marginBottom: 14,
    }}>
      <span style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-muted)',
        width: 140, flexShrink: 0,
      }}>
        {name}
      </span>
      <div style={{
        flex: 1, height: 8, borderRadius: 4,
        background: 'var(--border)',
        overflow: 'hidden',
      }}>
        <div style={{
          height: '100%', borderRadius: 4,
          width: `${score}%`,
          background: scoreColor(score),
          animation: `barGrow 0.8s ease ${delay}ms both`,
        }} />
      </div>
      <span style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700,
        color: scoreColor(score), width: 32, textAlign: 'right',
        flexShrink: 0,
      }}>
        {score}
      </span>
    </div>
  )
}

// ─── Main Page ──────────────────────────────────────────────

export default function ReportPage() {
  const [report, setReport] = useState<GovernanceReport | null>(null)
  const [company, setCompany] = useState('Your Company')

  useEffect(() => {
    const r = loadReport() as GovernanceReport | null
    const session = loadSession()
    setReport(r)
    setCompany(session.user?.company || 'Your Company')
    markStepComplete(3)
  }, [])

  // ─── Empty State ────────────────────────────────────────
  if (!report) {
    return (
      <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text-primary)' }}>
        <style>{keyframesCSS}</style>
        <Header />
        <div style={{
          maxWidth: 900, margin: '0 auto', padding: '120px 20px',
          textAlign: 'center',
          animation: 'fadeInPage 0.5s ease both',
        }}>
          <h1 style={{
            fontFamily: 'var(--font-heading)', fontSize: 24, fontWeight: 800,
            color: 'var(--text-primary)', marginBottom: 24, marginTop: 0,
          }}>
            Governance Report
          </h1>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 20, fontWeight: 700,
            color: 'var(--text-primary)', marginBottom: 8,
          }}>
            No report yet.
          </div>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 14, color: 'var(--text-muted)', marginBottom: 28,
          }}>
            Run a governance scan first.
          </div>
          <a
            href="/scan"
            className="report-btn"
            style={{
              fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700,
              color: 'var(--bg)', background: 'var(--accent)',
              textDecoration: 'none',
              padding: '12px 32px', borderRadius: 4,
              border: 'none',
              display: 'inline-block',
              letterSpacing: '0.02em',
              transition: 'all 150ms ease',
            }}
          >
            Go to Scan {'\u2192'}
          </a>
        </div>
      </div>
    )
  }

  // ─── Report Data ────────────────────────────────────────
  const autoFixed = report.violations.filter(v => v.fixApplied)
  const warnings = report.violations.filter(v => !v.fixApplied && v.severity === 'warn')
  const blocked = report.violations.filter(v => !v.fixApplied && v.severity === 'block')
  const delta = report.afterScore - report.overallScore

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text-primary)' }}>
      <style>{keyframesCSS}</style>
      <Header />

      <div style={{
        maxWidth: 900, margin: '0 auto', padding: '32px 20px 120px',
        animation: 'fadeInPage 0.5s ease both',
      }}>

        {/* ─── Header ──────────────────────────────────────── */}
        <div style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 4, padding: '32px 36px', marginBottom: 24,
        }}>
          <h1 style={{
            fontFamily: 'var(--font-heading)', fontSize: 24, fontWeight: 800,
            color: 'var(--text-primary)', marginBottom: 20, marginTop: 0,
          }}>
            Governance Report
          </h1>

          <div style={{
            display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px 20px',
          }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', letterSpacing: '0.06em' }}>Company</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-secondary)' }}>{company}</span>

            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', letterSpacing: '0.06em' }}>Design System</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-secondary)' }}>Acme Design System</span>

            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', letterSpacing: '0.06em' }}>Fixture</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-secondary)' }}>
              {report.fixtureName} <span style={{ color: 'var(--text-muted)' }}>from</span> {report.fixtureSource}
            </span>

            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', letterSpacing: '0.06em' }}>Date</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-secondary)' }}>{formatDate(report.timestamp)}</span>
          </div>
        </div>

        {/* ─── Score Card ──────────────────────────────────── */}
        <div style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 4, padding: '36px 36px 28px',
          marginBottom: 24,
          display: 'flex', flexDirection: 'column', alignItems: 'center',
        }}>
          <ScoreRing score={report.afterScore} size={120} />

          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-muted)',
            marginTop: 16, textAlign: 'center', lineHeight: 1.6,
          }}>
            <span style={{ color: scoreColor(report.overallScore), fontWeight: 700 }}>{report.overallScore}</span>
            <span style={{ color: 'var(--text-muted)', margin: '0 8px' }}>{'\u2192'}</span>
            <span style={{ color: scoreColor(report.afterScore), fontWeight: 700 }}>{report.afterScore}</span>
            <span style={{ color: 'var(--text-muted)', margin: '0 6px' }}>{'\u00B7'}</span>
            {delta > 0 ? (
              <span style={{
                color: 'var(--success)', fontWeight: 700,
                background: 'var(--success-dim)', padding: '2px 10px', borderRadius: 4,
                border: '1px solid color-mix(in srgb, var(--success) 25%, transparent)',
              }}>
                +{delta} points after governance
              </span>
            ) : (
              <span style={{ color: 'var(--text-muted)' }}>
                {delta === 0 ? 'no change' : `${delta} points`}
              </span>
            )}
          </div>

          {/* Summary pills */}
          <div style={{
            display: 'flex', gap: 10, marginTop: 20, flexWrap: 'wrap', justifyContent: 'center',
          }}>
            <span style={{
              fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
              color: 'var(--success)', background: 'var(--success-dim)',
              padding: '5px 14px', borderRadius: 4,
              border: '1px solid color-mix(in srgb, var(--success) 25%, transparent)',
            }}>
              {report.autoFixedCount} auto-fixed
            </span>
            <span style={{
              fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
              color: 'var(--warning)', background: 'var(--warning-dim)',
              padding: '5px 14px', borderRadius: 4,
              border: '1px solid color-mix(in srgb, var(--warning) 25%, transparent)',
            }}>
              {report.warningCount} warnings
            </span>
            <span style={{
              fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
              color: 'var(--error)', background: 'var(--error-dim)',
              padding: '5px 14px', borderRadius: 4,
              border: '1px solid color-mix(in srgb, var(--error) 25%, transparent)',
            }}>
              {report.blockedCount} blocked
            </span>
          </div>
        </div>

        {/* ─── Category Breakdown ──────────────────────────── */}
        <div style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 4, padding: '28px 36px', marginBottom: 24,
        }}>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 700,
            color: 'var(--text-primary)', marginBottom: 20,
            letterSpacing: '0.02em',
          }}>
            Category Breakdown
          </div>

          {report.categories.map((c, i) => (
            <CategoryBar key={c.key} name={c.name} score={c.score} delay={200 + i * 100} />
          ))}
        </div>

        {/* ─── Auto-Fixed Section ──────────────────────────── */}
        {autoFixed.length > 0 && (
          <div>
            <SectionHeader label="AUTO-FIXED" count={autoFixed.length} color="var(--success)" dimColor="var(--success-dim)" />
            {autoFixed.map((v, i) => (
              <AutoFixedCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Warnings Section ────────────────────────────── */}
        {warnings.length > 0 && (
          <div>
            <SectionHeader label="WARNINGS" count={warnings.length} color="var(--warning)" dimColor="var(--warning-dim)" />
            {warnings.map((v, i) => (
              <WarningCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Blocked Section ─────────────────────────────── */}
        {blocked.length > 0 && (
          <div>
            <SectionHeader label="BLOCKED" count={blocked.length} color="var(--error)" dimColor="var(--error-dim)" />
            {blocked.map((v, i) => (
              <BlockedCard key={v.id} v={v} index={i} />
            ))}
          </div>
        )}

        {/* ─── Bottom Action Bar ───────────────────────────── */}
        <div className="action-bar-mobile" style={{
          display: 'flex', gap: 10, marginTop: 48, flexWrap: 'wrap',
          padding: '24px 0',
          borderTop: '1px solid var(--border)',
          position: 'sticky', bottom: 0,
          background: 'var(--bg)',
          zIndex: 10,
        }}>
          <CopyButton
            label="Copy as JSON"
            onCopy={() => navigator.clipboard.writeText(reportToJSON(report))}
          />
          <CopyButton
            label="Copy as Markdown"
            onCopy={() => navigator.clipboard.writeText(reportToMarkdown(report, company))}
          />
          <CopyButton
            label="Share Report"
            onCopy={() => navigator.clipboard.writeText(window.location.href)}
          />
          <div style={{ flex: 1 }} />
          <a
            href="/scan"
            className="report-btn btn-mobile-full"
            style={{
              fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700,
              padding: '10px 24px', borderRadius: 4, cursor: 'pointer',
              background: 'var(--accent)', color: 'var(--bg)',
              border: 'none', textDecoration: 'none',
              letterSpacing: '0.02em',
              display: 'inline-flex', alignItems: 'center', gap: 6,
              transition: 'all 150ms ease',
            }}
          >
            Scan another {'\u2192'}
          </a>
        </div>

        {/* ─── CTA: MCP Integration ────────────────────────── */}
        <a
          href="/integrate"
          className="report-btn"
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '24px 32px', marginTop: 24,
            background: 'var(--surface)', border: '1px solid var(--border)',
            borderRadius: 4, textDecoration: 'none',
            transition: 'all 150ms ease',
          }}
        >
          <div>
            <div style={{
              fontFamily: 'var(--font-mono)', fontSize: 16, fontWeight: 700,
              color: 'var(--text-primary)', marginBottom: 6,
            }}>
              Set up MCP integration
            </div>
            <div style={{
              fontFamily: 'var(--font-mono)', fontSize: 13, color: 'var(--text-muted)', lineHeight: 1.5,
            }}>
              Enforce governance automatically in your AI coding workflow.
            </div>
          </div>
          <span style={{
            fontFamily: 'var(--font-mono)', fontSize: 22, color: 'var(--accent)',
            flexShrink: 0, marginLeft: 20,
          }}>
            {'\u2192'}
          </span>
        </a>

      </div>
    </div>
  )
}
